# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 64bd76d0b2b03728ee3ff13925cc7a4fbb1c97b8b41f2e970375476d3e73da3c672a96b3fe6648457b09f30b0c9f1b041f09ea795048a0a360fa18f189863973

test:
  secret_key_base: 038cb89e5a24bbca886b9bf334285c458c8bebad58319d5ceaa8c260b7a9ecdd56093ab1b7c98ed1eb79ef4d447bb04dac18737065fca7ea05915e13d2ed3046

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
